/**
 * Off-chain Groth16 verification.
 *
 * Verifies a Groth16 proof against a verification key and public inputs.
 * This is the reference implementation used for testing — the Bitcoin Script
 * version is generated by verify-script.ts.
 */

import type { Groth16Proof, VerificationKey, G1Point, Fp } from '../types.js';
import { g1Add, g1Mul, g1Neg, g1OnCurve } from '../bn254/g1.js';
import { g2OnCurve } from '../bn254/g2.js';
import { R } from '../bn254/constants.js';
import { checkPairingProduct } from '../bn254/pairing.js';

/**
 * Verify a Groth16 proof.
 *
 * The verification equation is:
 *   e(A, B) = e(alpha, beta) · e(L, gamma) · e(C, delta)
 *
 * Where L = IC[0] + Σ_{i=1}^{l} input[i-1] · IC[i]
 *
 * Rearranged for a single product-of-pairings check:
 *   e(A, B) · e(-alpha, beta) · e(-L, gamma) · e(-C, delta) = 1
 *
 * @param vk     Verification key
 * @param proof  Groth16 proof (A, B, C)
 * @param inputs Public inputs (field elements in Fr)
 * @returns true if the proof is valid
 */
export function verifyGroth16(
  vk: VerificationKey,
  proof: Groth16Proof,
  inputs: Fp[],
): boolean {
  // Validate input count matches IC length
  if (inputs.length + 1 !== vk.ic.length) {
    throw new Error(
      `Groth16 verify: expected ${vk.ic.length - 1} public inputs, got ${inputs.length}`,
    );
  }

  // Validate inputs are in the scalar field
  for (let i = 0; i < inputs.length; i++) {
    if (inputs[i]! < 0n || inputs[i]! >= R) {
      throw new Error(`Groth16 verify: public input[${i}] is not in Fr`);
    }
  }

  // Validate proof points are on their curves
  if (!g1OnCurve(proof.a)) throw new Error('Groth16 verify: proof.A not on G1');
  if (!g2OnCurve(proof.b)) throw new Error('Groth16 verify: proof.B not on G2');
  if (!g1OnCurve(proof.c)) throw new Error('Groth16 verify: proof.C not on G1');

  // Compute L = IC[0] + Σ input[i] · IC[i+1]
  let l: G1Point = vk.ic[0]!;
  for (let i = 0; i < inputs.length; i++) {
    if (inputs[i]! !== 0n) {
      l = g1Add(l, g1Mul(vk.ic[i + 1]!, inputs[i]!));
    }
  }

  // Check: e(A, B) · e(-alpha, beta) · e(-L, gamma) · e(-C, delta) = 1
  return checkPairingProduct([
    { g1: proof.a, g2: proof.b },
    { g1: g1Neg(vk.alpha), g2: vk.beta },
    { g1: g1Neg(l), g2: vk.gamma },
    { g1: g1Neg(proof.c), g2: vk.delta },
  ]);
}
